
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Panels;

import NOYAU.configuration.ParametrageInterop;
import NOYAU.structure.Application;
import UI.Frames.ModifierElement;
import java.awt.Container;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author antoi
 */
public class AjouterModifierFlux extends javax.swing.JPanel {
    private Container parentContainer;
    private ParametrageInterop pi = new ParametrageInterop();
    private List<Application> lesApplications;
    private DefaultComboBoxModel dml = new DefaultComboBoxModel();
    private List<DmlRow> dmlr = new ArrayList();
    private int i = 0;
    /**
     * Creates new form AjouterModifierFlux
     * @param c
     */
    public AjouterModifierFlux(Container c) {
        this.parentContainer = c;
        initComponents();    
        initComboBoxes();
    }
    
    public AjouterModifierFlux(Object o, Container c) {
        this.pi = (ParametrageInterop) o;
        this.parentContainer = c;
        
        initComponents();
        initComboBoxes();
                
        this.jTextFieldAdresseIP.setText(pi.getAdresseIp());        
        this.jTextFieldPort.setText(String.valueOf(pi.getPort()));        
        
        switch(pi.getSens()){
           case 1 -> this.jComboBoxApplicationSens.setSelectedItem(Sens.ENVOI.toString());
           case 2 -> this.jComboBoxApplicationSens.setSelectedItem(Sens.RECEPTION.toString());
       }
        
        switch(pi.getIsActif()){
           case false -> this.jComboBoxApplicationIsActif.setSelectedItem(IsActif.INACTIF.toString());
           case true -> this.jComboBoxApplicationIsActif.setSelectedItem(IsActif.ACTIF.toString());
       }
       
        this.dmlr.forEach(a -> {
            if(a.rowObjectId == this.pi.getApplication().getAppId()){
                System.out.println(this.dml.getElementAt(a.rowId));
                this.jComboBoxApplication.setSelectedItem(this.dml.getElementAt(a.rowId));
            }
//            System.out.println(a.rowId);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldAdresseIP = new javax.swing.JTextField();
        jButtonSauvegarder = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jTextFieldPort = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxApplication = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxApplicationSens = new javax.swing.JComboBox<>();
        jComboBoxApplicationIsActif = new javax.swing.JComboBox<>();

        jLabel1.setText("modifier flux");

        jButtonSauvegarder.setText("Sauvegarder");
        jButtonSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSauvegarderActionPerformed(evt);
            }
        });

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        jLabel2.setText("Adresse IP");

        jLabel3.setText("Port");

        jLabel4.setText("Sens");

        jLabel5.setText("isActif");

        jLabel6.setText("Application");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxApplication, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldAdresseIP)
                            .addComponent(jTextFieldPort)
                            .addComponent(jComboBoxApplicationSens, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxApplicationIsActif, 0, 121, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButtonSauvegarder)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSupprimer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAdresseIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxApplicationSens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxApplicationIsActif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxApplication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSauvegarder)
                    .addComponent(jButtonSupprimer))
                .addGap(66, 66, 66))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSauvegarderActionPerformed
        
        int i = JOptionPane.showConfirmDialog(this, "Sauvegarder la configuration ?", "SAUVEGARDER", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
//            System.out.println(this.pi.toString());
            pi.setAdresseIp(this.jTextFieldAdresseIP.getText());
            pi.setPort(Integer.parseInt(this.jTextFieldPort.getText()));
            switch(Sens.valueOf(this.jComboBoxApplicationSens.getSelectedItem().toString())){
               case Sens.ENVOI -> this.pi.setSens(1);
               case Sens.RECEPTION -> this.pi.setSens(2);
               default -> {System.out.println("default");}
            }
            switch(IsActif.valueOf(this.jComboBoxApplicationIsActif.getSelectedItem().toString())){
               case IsActif.ACTIF -> this.pi.setIsActif(true);
               case IsActif.INACTIF -> this.pi.setIsActif(false);
               default -> {System.out.println("default");}
            }
            this.pi.setApplication(Application.getApplication(this.dmlr.get(this.dml.getIndexOf(this.jComboBoxApplication.getSelectedItem())).rowObjectId));

            if(pi.getConfId() == 0){
                this.pi.ajouterParametrageInterop();
            } else {
                this.pi.modifierParametrageInterop();
            }
            ((ModifierElement) this.parentContainer).dispose();
        }

    }//GEN-LAST:event_jButtonSauvegarderActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Supprimer cette interface ?", "SUPPRIMER", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            this.pi.supprimerParametrageInterop();
            ((ModifierElement) this.parentContainer).dispose();
        }
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private enum Sens{
        ENVOI,
        RECEPTION
    }
    
    private enum IsActif{
        ACTIF,
        INACTIF
    }

    private class DmlRow{
        private int rowId;
        private int rowObjectId;
        
        public DmlRow(int rowId, int rowObjectId){
            this.rowId = rowId;
            this.rowObjectId = rowObjectId;
        }

        public int getRowId() {
            return rowId;
        }

        public int rowObjectId() {
            return rowObjectId;
        }
    }
    
    private void initComboBoxes(){
        this.lesApplications = Application.getLesApplications();
        lesApplications.forEach(app -> {
            DmlRow d = new DmlRow(this.i, app.getAppId());
            this.dmlr.add(d);
            this.dml.insertElementAt(app.getAppLibelle(), this.dmlr.indexOf(d));
            this.i++;
        });
        
        this.jComboBoxApplication.setModel(dml);
        
        
        this.jComboBoxApplicationSens.addItem(Sens.ENVOI.toString());
        this.jComboBoxApplicationSens.addItem(Sens.RECEPTION.toString());
        
        this.jComboBoxApplicationIsActif.addItem(IsActif.ACTIF.toString());
        this.jComboBoxApplicationIsActif.addItem(IsActif.INACTIF.toString());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSauvegarder;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JComboBox<String> jComboBoxApplication;
    private javax.swing.JComboBox<String> jComboBoxApplicationIsActif;
    private javax.swing.JComboBox<String> jComboBoxApplicationSens;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldAdresseIP;
    private javax.swing.JTextField jTextFieldPort;
    // End of variables declaration//GEN-END:variables
}
