/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Panels;

import NOYAU.structure.Identifiant;
import NOYAU.structure.Intervenant;
import NOYAU.structure.Role;
import UI.Frames.ModifierElement;
import UI.Frames.ModifierIdentifiants;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author antoi
 */
public class AjouterModifierIntervenant extends javax.swing.JPanel {
    private Container parentContainer;
    private Intervenant inter = new Intervenant();
    private List<Role> lesRoles;
    private DefaultComboBoxModel dml = new DefaultComboBoxModel();
    private List<DmlRow> dmlr = new ArrayList();
    private int i = 0;
    /**
     * Creates new form AjouterModifierIntervenant
     */
    public AjouterModifierIntervenant(Container c) {
        this.parentContainer = c;
        initComponents();
        initComboBoxes();
    }
    
    public AjouterModifierIntervenant(Object o, Container c) {
        this.parentContainer = c;
        this.inter = (Intervenant) o;
        
        initComponents();
        
        this.jTextFieldMatricule.setText(this.inter.getMatricule());
        this.jTextFieldNom.setText(this.inter.getNom());
        this.jTextFieldPrenom.setText(this.inter.getPrenom());
        
        initComboBoxes();
        
        this.dmlr.forEach(a -> {
            if(a.rowObjectId == this.inter.getRole().getRolId()){
                System.out.println(this.dml.getElementAt(a.rowId));
                this.jComboBoxRole.setSelectedItem(this.dml.getElementAt(a.rowId));
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMatricule = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jComboBoxRole = new javax.swing.JComboBox<>();
        jButtonModifierIdentifiants = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonSauvegarder = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();

        jLabel1.setText("modifier intervenant");

        jLabel2.setText("Matricule");

        jLabel3.setText("Nom");

        jLabel4.setText("Prenom");

        jButtonModifierIdentifiants.setText("Modifier identifiants");
        jButtonModifierIdentifiants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierIdentifiantsActionPerformed(evt);
            }
        });

        jLabel5.setText("Role");

        jLabel6.setText("Identifiants");

        jButtonSauvegarder.setText("Sauvegarder");
        jButtonSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSauvegarderActionPerformed(evt);
            }
        });

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonModifierIdentifiants))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButtonSauvegarder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSupprimer)))
                .addGap(41, 160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButtonModifierIdentifiants))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSauvegarder)
                    .addComponent(jButtonSupprimer))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModifierIdentifiantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierIdentifiantsActionPerformed
        System.out.println("int_id = " + this.inter.getIntId());
        final ModifierIdentifiants mi;
        if(this.inter.getIdentifiant() != null){
            mi = new ModifierIdentifiants((Component) parentContainer, this.inter);
            System.out.println(this.inter.getIdentifiant().getLogin());
        } else {
            this.inter.setIdentifiants(new Identifiant());
            mi = new ModifierIdentifiants((Component) parentContainer, this.inter);
            System.out.println("Identifiant null");
        }
        
        System.out.println((Object)this.inter);
        
        mi.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                ((Component) parentContainer).setEnabled(true);
                ((Component) parentContainer).setVisible(true);
            } 
        });
        ((Component) parentContainer).setEnabled(false);
        mi.setVisible(true);
        mi.toFront();
    }//GEN-LAST:event_jButtonModifierIdentifiantsActionPerformed

    private void jButtonSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSauvegarderActionPerformed

        
        int i = JOptionPane.showConfirmDialog(this, "Sauvegarder la configuration ?", "SAUVEGARDER", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
//            System.out.println(this.pi.toString());

            
            inter.setNom(this.jTextFieldNom.getText());
            inter.setPrenom(this.jTextFieldPrenom.getText());
            inter.setMatricule(this.jTextFieldMatricule.getText());
            
            inter.setRole(Role.getRole(this.dmlr.get(this.dml.getIndexOf(this.jComboBoxRole.getSelectedItem())).rowObjectId));
            
            if(inter.getIntId() == 0){
                this.inter.ajouterIntervenant();
            } else {
                this.inter.modifierIntervenant();
            }
            
            if(inter.getIdentifiant().getIdenId() == 0){
                this.inter.getIdentifiant().ajouterIdentifiant();
            } else {
                this.inter.getIdentifiant().modifierIdentifiant();
            }
            
            System.out.println("idenId = " + this.inter.getIdentifiant().getIdenId());
            System.out.println("login = " + this.inter.getIdentifiant().getLogin());
            
            ((ModifierElement) this.parentContainer).dispose();
        }

        
    }//GEN-LAST:event_jButtonSauvegarderActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void initComboBoxes(){
        this.lesRoles = Role.getLesRoles();
        lesRoles.forEach(rol -> {
            DmlRow d = new DmlRow(this.i, rol.getRolId());
            this.dmlr.add(d);
            this.dml.insertElementAt(rol.getLibelle(), this.dmlr.indexOf(d));
            this.i++;
        });
        
        this.jComboBoxRole.setModel(dml);
        
        
//        this.jComboBoxApplicationSens.addItem(Sens.ENVOI.toString());
//        this.jComboBoxApplicationSens.addItem(Sens.RECEPTION.toString());
//        
//        this.jComboBoxApplicationIsActif.addItem(IsActif.ACTIF.toString());
//        this.jComboBoxApplicationIsActif.addItem(IsActif.INACTIF.toString());
    }
    
    
    private class DmlRow{
        private int rowId;
        private int rowObjectId;
        
        public DmlRow(int rowId, int rowObjectId){
            this.rowId = rowId;
            this.rowObjectId = rowObjectId;
        }

        public int getRowId() {
            return rowId;
        }

        public int rowObjectId() {
            return rowObjectId;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModifierIdentifiants;
    private javax.swing.JButton jButtonSauvegarder;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JComboBox<String> jComboBoxRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldMatricule;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    // End of variables declaration//GEN-END:variables
}
