/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Panels;

import UI.Frames.JFrameMain;
import UI.Static.IHMColors;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author antoi
 */
public class BoutonMenu extends JPanel {

    private JFrame parentFrame;
    private JPanel selectedJPanel;
    private String buttonName;
    /**
     * Creates new form BoutonMenu
     */
    public BoutonMenu(JPanel selectedJPanel, String buttonName, JFrame jf) {
        this.parentFrame = jf;
        this.selectedJPanel = selectedJPanel;
        this.buttonName = buttonName;
        initComponents();
        this.setBackground(IHMColors.JLABEL_BUTTON_MENU_DEFAULT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 51));
        setPreferredSize(new java.awt.Dimension(60, 60));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jLabel1.setText(this.buttonName);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.clickingJPanel(this);
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        this.clickingJPanel(this);
        System.out.println("Tu as cliqué sur : " + this.buttonName);
    }//GEN-LAST:event_formMousePressed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.enteringJPanel(this);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.exitingJPanel(this);
    }//GEN-LAST:event_formMouseExited

public void clickingJPanel(JPanel jp){
        if(((JFrameMain)this.parentFrame).getSelectedJPanel() != null && ((JFrameMain)this.parentFrame).getSelectedJPanel() != jp){
            ((JFrameMain)this.parentFrame).getSelectedJPanel().setBackground(IHMColors.JLABEL_BUTTON_MENU_DEFAULT);
        }
        
        jp.setBackground(IHMColors.JLABEL_BUTTON_MENU_SELECTED);
        ((JFrameMain)this.parentFrame).setSelectedJPanel(this);
//        this.selectedJPanel = ((JFrameMain)this.parentFrame).getSelectedJPanel();
    }
    
    public void exitingJPanel(JPanel jp){
        if(((JFrameMain)this.parentFrame).getSelectedJPanel() == jp){
            
        } else {
            jp.setBackground(IHMColors.JLABEL_BUTTON_MENU_DEFAULT);
        }
    }
    
    public void enteringJPanel(JPanel jp){
        if(jp != ((JFrameMain)this.parentFrame).getSelectedJPanel() || ((JFrameMain)this.parentFrame).getSelectedJPanel() == null){
            jp.setBackground(IHMColors.JLABEL_BUTTON_MENU_ENTERED);
        }
    }
    
    public void pressingJPanel(JPanel jp){
        jp.setBackground(IHMColors.JLABEL_BUTTON_MENU_CLICKED);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLabel1() {
        return jLabel1;
    }



}
