/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Panels;

import NOYAU.configuration.ParametrageInterop;
import UI.Frames.ModifierElement;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author antoi
 */
public class GestionFlux extends javax.swing.JPanel {
    private Object currentWindow;
    private DefaultListModel dlm;
    /**
     * Creates new form GestionFlux
     */
    public GestionFlux(Component parentComponent) {
        this.currentWindow = parentComponent;
        
        initJListDML();
        initComponents();
        
        jList1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                JList list = (JList)evt.getSource();
                if (evt.getClickCount() == 2) {

                    // Double-click detected
                    int index = list.locationToIndex(evt.getPoint());
                    System.out.println("Double Clic");
                    initModifierFlux(dlm.getElementAt(index));
                } else if (evt.getClickCount() == 3) {

                    // Triple-click detected
                    int index = list.locationToIndex(evt.getPoint());
                    System.out.println("Triple Clic");
                }
            }
        });
        this.jList1.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCreerFlux = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        jButtonCreerFlux.setText("Créer Flux");
        jButtonCreerFlux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerFluxActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(677, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCreerFlux)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCreerFlux)
                .addContainerGap(179, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreerFluxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerFluxActionPerformed
        initAjouterFlux();
    }//GEN-LAST:event_jButtonCreerFluxActionPerformed

    private void initAjouterModifierFlux(Object o){
        final ModifierElement me;
        if(o == null){
            me = new ModifierElement((Component) currentWindow, this.getClass());
        } else {
            me = new ModifierElement((Component) currentWindow, this.getClass(), o);
        }
        
        
        me.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                ((Component) currentWindow).setEnabled(true);
                ((Component) currentWindow).setVisible(true);
                initJListDML();
                jList1.setModel(dlm);
            } 
        });
        ((Component) currentWindow).setEnabled(false);
        me.setVisible(true);
        me.toFront();  
    }
    
    private void initAjouterFlux(){
        initAjouterModifierFlux(null);
    }
    
    private void initModifierFlux(Object o){
        initAjouterModifierFlux(o);
    }
    
    public void initJListDML(){
        this.dlm = new DefaultListModel();
        
        ParametrageInterop.getLesParam().forEach(i -> {
                this.dlm.addElement(i);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreerFlux;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
