/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Frames;

import UI.Panels.BoutonMenu;
import UI.Static.IHMColors;
import javax.swing.JPanel;

/**
 *
 * @author antoi
 */
public class JFrameMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameMain.class.getName());
    private JPanel selectedJPanel;
    

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        IHMColors.initColors();
        initComponents();
//        initBoutonTest();
//        initBoutonTest3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackGround = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jPanelLeft = new javax.swing.JPanel();
        jPanelButton1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelButton2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelTEST = new BoutonMenu(this.selectedJPanel, "TST", this);
        jPanelCenter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBackGround.setBackground(IHMColors.GLOBAL_BACKGROUND_COLOR);

        jPanelHeader.setBackground(IHMColors.GLOBAL_BACKGROUND_COLOR);

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanelLeft.setBackground(IHMColors.GLOBAL_BACKGROUND_COLOR);

        jPanelButton1.setBackground(IHMColors.GLOBAL_BACKGROUND_COLOR);
        jPanelButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelButton1MousePressed(evt);
            }
        });

        jLabel1.setText("B1");

        javax.swing.GroupLayout jPanelButton1Layout = new javax.swing.GroupLayout(jPanelButton1);
        jPanelButton1.setLayout(jPanelButton1Layout);
        jPanelButton1Layout.setHorizontalGroup(
            jPanelButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButton1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelButton1Layout.setVerticalGroup(
            jPanelButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButton1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );

        jPanelButton2.setBackground(IHMColors.GLOBAL_BACKGROUND_COLOR);
        jPanelButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelButton2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelButton2MousePressed(evt);
            }
        });

        jLabel2.setText("B2");

        javax.swing.GroupLayout jPanelButton2Layout = new javax.swing.GroupLayout(jPanelButton2);
        jPanelButton2.setLayout(jPanelButton2Layout);
        jPanelButton2Layout.setHorizontalGroup(
            jPanelButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButton2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelButton2Layout.setVerticalGroup(
            jPanelButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButton2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanelTESTLayout = new javax.swing.GroupLayout(jPanelTEST);
        jPanelTEST.setLayout(jPanelTESTLayout);
        jPanelTESTLayout.setHorizontalGroup(
            jPanelTESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelTESTLayout.setVerticalGroup(
            jPanelTESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLeftLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelTEST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanelButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(jPanelTEST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );

        jPanelCenter.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1128, Short.MAX_VALUE)
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelBackGroundLayout = new javax.swing.GroupLayout(jPanelBackGround);
        jPanelBackGround.setLayout(jPanelBackGroundLayout);
        jPanelBackGroundLayout.setHorizontalGroup(
            jPanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackGroundLayout.createSequentialGroup()
                .addComponent(jPanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelBackGroundLayout.setVerticalGroup(
            jPanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackGroundLayout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelButton1MouseEntered
        enteringJPanel(this.jPanelButton1);
    }//GEN-LAST:event_jPanelButton1MouseEntered

    private void jPanelButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelButton1MouseExited
        exitingJPanel(this.jPanelButton1);
    }//GEN-LAST:event_jPanelButton1MouseExited

    private void jPanelButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelButton1MouseClicked
        clickingJPanel(this.jPanelButton1);
    }//GEN-LAST:event_jPanelButton1MouseClicked

    private void jPanelButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelButton1MousePressed
        pressingJPanel(this.jPanelButton1);
    }//GEN-LAST:event_jPanelButton1MousePressed

    private void jPanelButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelButton2MouseClicked
        clickingJPanel(this.jPanelButton2);
    }//GEN-LAST:event_jPanelButton2MouseClicked

    private void jPanelButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelButton2MouseEntered
        enteringJPanel(this.jPanelButton2);
    }//GEN-LAST:event_jPanelButton2MouseEntered

    private void jPanelButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelButton2MouseExited
        exitingJPanel(this.jPanelButton2);
    }//GEN-LAST:event_jPanelButton2MouseExited

    private void jPanelButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelButton2MousePressed
        pressingJPanel(this.jPanelButton2);
    }//GEN-LAST:event_jPanelButton2MousePressed

    
    public void clickingJPanel(JPanel jp){
        if(this.selectedJPanel != null && this.selectedJPanel != jp){
            this.selectedJPanel.setBackground(IHMColors.JLABEL_BUTTON_MENU_DEFAULT);
        }
        jp.setBackground(IHMColors.JLABEL_BUTTON_MENU_SELECTED);
        this.selectedJPanel = jp;
    }
    
    public void exitingJPanel(JPanel jp){
        if(this.selectedJPanel == jp){
            
        } else {
            jp.setBackground(IHMColors.JLABEL_BUTTON_MENU_DEFAULT);
        }
    }
    
    public void enteringJPanel(JPanel jp){
        if(jp != this.selectedJPanel || this.selectedJPanel == null){
            jp.setBackground(IHMColors.JLABEL_BUTTON_MENU_ENTERED);
        }
    }
    
    public void pressingJPanel(JPanel jp){
        jp.setBackground(IHMColors.JLABEL_BUTTON_MENU_CLICKED);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelBackGround;
    private javax.swing.JPanel jPanelButton1;
    private javax.swing.JPanel jPanelButton2;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelTEST;
    // End of variables declaration//GEN-END:variables

    private UI.Panels.BoutonMenu TEST2;
    private UI.Panels.BoutonMenu TEST3;
    
    public void initBoutonTest(){
        this.TEST2 = new BoutonMenu(this.selectedJPanel, "B4", this);
        TEST2.setBackground(IHMColors.JLABEL_BUTTON_MENU_DEFAULT);
        
        
        javax.swing.GroupLayout TEST2Layout = new javax.swing.GroupLayout(TEST2);
        TEST2.setLayout(TEST2Layout);
        
        
        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLeftLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
//                    .addComponent(TESTBOUTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEST2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLeftLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
//                    .addComponent(TESTBOUTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEST2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        
//        pack();
//        this.jPanelLeft.getLayout().addLayoutComponent("test", TEST2);
//        this.jPanelLeft.getLayout().addLayoutComponent(name, this);
//        TEST2Layout.setHorizontalGroup(
//            TEST2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(TEST2Layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(jLabel3)
//                .addContainerGap(16, Short.MAX_VALUE))
//        );
//        TEST2Layout.setVerticalGroup(
//            TEST2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TEST2Layout.createSequentialGroup()
//                .addContainerGap(22, Short.MAX_VALUE)
//                .addComponent(jLabel3)
//                .addGap(22, 22, 22))
//        );
        
    }
    
    public void initBoutonTest3(){
        this.TEST3 = new BoutonMenu(this.selectedJPanel, "B5", this);
        TEST3.setBackground(IHMColors.JLABEL_BUTTON_MENU_DEFAULT);
        
        
        javax.swing.GroupLayout TEST3Layout = new javax.swing.GroupLayout(TEST3);
        TEST3.setLayout(TEST3Layout);
        
        
        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLeftLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
//                    .addComponent(TESTBOUTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEST3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLeftLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
//                    .addComponent(TESTBOUTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEST3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        
//        pack();
//        this.jPanelLeft.getLayout().addLayoutComponent("test", TEST2);
//        this.jPanelLeft.getLayout().addLayoutComponent(name, this);
//        TEST2Layout.setHorizontalGroup(
//            TEST2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(TEST2Layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(jLabel3)
//                .addContainerGap(16, Short.MAX_VALUE))
//        );
//        TEST2Layout.setVerticalGroup(
//            TEST2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TEST2Layout.createSequentialGroup()
//                .addContainerGap(22, Short.MAX_VALUE)
//                .addComponent(jLabel3)
//                .addGap(22, 22, 22))
//        );
        
    }

    public JPanel getSelectedJPanel() {
        return selectedJPanel;
    }

    public void setSelectedJPanel(JPanel selectedJPanel) {
        this.selectedJPanel = selectedJPanel;
    }
    
    
    
}
