/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Frames;

import UI.Panels.AjouterModifierFlux;
import UI.Panels.AjouterModifierIntervenant;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author antoi
 */
public class ModifierElement extends javax.swing.JFrame {
    private Component parentComponent;
    private AjouterModifierIntervenant ajouterModifierIntervenant1;
    private AjouterModifierFlux ajouterModifierFlux;
    /**
     * Creates new form ModifierElement
     */
    public ModifierElement(Component parentComponent, Class classe) {
       this.parentComponent = parentComponent;
       switch(classe.getName()){
           case "UI.Panels.GestionFlux":
               ajouterModifierFlux = new AjouterModifierFlux(this);
               this.initAjouterModifierFluxPanel();
               break;
           case "UI.Panels.GestionIntervenants":
               ajouterModifierIntervenant1 = new AjouterModifierIntervenant(this);
               this.initAjouterModifierIntervenantPanel();
               break;
           default:
       }
       initComponents(); 
    }
    
    public ModifierElement(Component parentComponent, Class classe, Object o) {
       this.parentComponent = parentComponent;
       System.out.println(o.toString());
       
       switch(classe.getName()){
           case "UI.Panels.GestionFlux":
               ajouterModifierFlux = new AjouterModifierFlux(o, this);
               this.initAjouterModifierFluxPanel();
               break;
           case "UI.Panels.GestionIntervenants":
               ajouterModifierIntervenant1 = new AjouterModifierIntervenant(o, this);
               this.initAjouterModifierIntervenantPanel();
               break;
           default:
       }
       initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int i = JOptionPane.showConfirmDialog(this, "Voulez-vous quitter la saisie ? Les informations ne seront pas enregistrées", "ATTENTION", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    
    
    private void initAjouterModifierIntervenantPanel(){
         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ajouterModifierIntervenant1, javax.swing.GroupLayout.DEFAULT_SIZE, 1233, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ajouterModifierIntervenant1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );
        pack();
    }  
    
    private void initAjouterModifierFluxPanel(){
         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ajouterModifierFlux, javax.swing.GroupLayout.DEFAULT_SIZE, 1233, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ajouterModifierFlux, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );
        pack();
    }
    

    

    /**
     * @param args the command line arguments
     */
////////////    public static void main(String args[]) {
////////////        /* Set the Nimbus look and feel */
////////////        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
////////////        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
////////////         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
////////////         */
////////////        try {
////////////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
////////////                if ("Nimbus".equals(info.getName())) {
////////////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
////////////                    break;
////////////                }
////////////            }
////////////        } catch (ClassNotFoundException ex) {
////////////            java.util.logging.Logger.getLogger(ModifierElement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////////////        } catch (InstantiationException ex) {
////////////            java.util.logging.Logger.getLogger(ModifierElement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////////////        } catch (IllegalAccessException ex) {
////////////            java.util.logging.Logger.getLogger(ModifierElement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////////////        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
////////////            java.util.logging.Logger.getLogger(ModifierElement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////////////        }
////////////        //</editor-fold>
////////////
////////////        /* Create and display the form */
////////////        java.awt.EventQueue.invokeLater(new Runnable() {
////////////            public void run() {
////////////                new ModifierElement().setVisible(true);
////////////            }
////////////        });
////////////    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
